# Generated by Django 5.2.12 on 2026-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watermeasurement',
            new_name='water_measu_owner_i_421842_idx',
            old_name='water_measu_owner_i_999559_idx',
        ),
        migrations.RenameIndex(
            model_name='watermeasurement',
            new_name='water_measu_source_272d0c_idx',
            old_name='water_measu_source__1779aa_idx',
        ),
        migrations.RenameIndex(
            model_name='watermeasurement',
            new_name='water_measu_is_publ_68e9db_idx',
            old_name='water_measu_is_publ_90d704_idx',
        ),
        migrations.RenameIndex(
            model_name='watermeasurement',
            new_name='water_measu_externa_288da3_idx',
            old_name='water_measu_externa_93f1f5_idx',
        ),
    ]
