# Generated by Django 5.2.12 on 2026-03-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_watermeasurement_aggregate_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watermeasurement',
            new_name='water_measu_externa_5a70ba_idx',
            old_name='water_measu_externa_0bcab0_idx',
        ),
    ]
