# Generated by Django 5.2.12 on 2026-03-27 09:47

from django.conf import settings
from django.db.models import Count, OuterRef, Q, Subquery
from django.db import migrations, models


def populate_station_summaries(apps, schema_editor):
    Station = apps.get_model("measurements", "Station")
    WaterMeasurement = apps.get_model("measurements", "WaterMeasurement")
    db_alias = schema_editor.connection.alias

    latest_measurements = WaterMeasurement.objects.using(db_alias).filter(
        station=OuterRef("pk"),
        is_public=True,
    ).order_by("-sample_date", "-sample_time", "-created_at")

    stations_to_update = []
    annotated_stations = (
        Station.objects.using(db_alias)
        .filter(source_dataset="gemstat")
        .annotate(
            public_measurement_count=Count("measurements", filter=Q(measurements__is_public=True)),
            latest_measurement_id_value=Subquery(latest_measurements.values("id")[:1]),
            latest_sample_date_value=Subquery(latest_measurements.values("sample_date")[:1]),
            latest_sample_time_value=Subquery(latest_measurements.values("sample_time")[:1]),
        )
    )

    for station in annotated_stations.iterator():
        station.measurement_count = getattr(station, "public_measurement_count", 0) or 0
        station.latest_measurement_id = getattr(station, "latest_measurement_id_value", None)
        station.latest_sample_date = getattr(station, "latest_sample_date_value", None)
        station.latest_sample_time = getattr(station, "latest_sample_time_value", None)
        stations_to_update.append(station)

    if stations_to_update:
        Station.objects.using(db_alias).bulk_update(
            stations_to_update,
            ["measurement_count", "latest_measurement_id", "latest_sample_date", "latest_sample_time"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_drop_legacy_measurement_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latest_measurement_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='latest_sample_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='latest_sample_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='measurement_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['source_dataset', 'name', 'external_station_id'], name='stations_source__982089_idx'),
        ),
        migrations.AddIndex(
            model_name='watermeasurement',
            index=models.Index(condition=models.Q(('is_public', True)), fields=['station', '-sample_date', '-sample_time', '-created_at'], name='water_measu_pub_latest_idx'),
        ),
        migrations.RunPython(populate_station_summaries, migrations.RunPython.noop),
    ]
