# Generated by Django 5.2.12 on 2026-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedfilter',
            new_name='generated_f_owner_i_a80439_idx',
            old_name='generated_f_owner_i_0b6945_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedfilter',
            new_name='generated_f_study_i_9c2cc3_idx',
            old_name='generated_f_study_i_8b5b90_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedfilter',
            new_name='generated_f_status_8c8d89_idx',
            old_name='generated_f_status_36035c_idx',
        ),
    ]
