# Generated by Django 5.2.12 on 2026-03-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='study',
            new_name='studies_owner_i_81b5f6_idx',
            old_name='studies_stu_owner_i_a54fa0_idx',
        ),
        migrations.RenameIndex(
            model_name='study',
            new_name='studies_status_f3e047_idx',
            old_name='studies_stu_status_4a713d_idx',
        ),
    ]
